//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AnbarGhataatYadaki
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string NameGheteh { get; set; }
        public string ShomarehFani { get; set; }
        public Nullable<long> Mojoodi { get; set; }
        public Nullable<long> NoghtehSefaresh { get; set; }
        public string Discription { get; set; }
    }
}
