//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GhataatMasrafiMashinAlat
    {
        public long ID { get; set; }
        public Nullable<long> IDShenasnamehMoshinAlat { get; set; }
        public Nullable<long> IDAnbarGhataatYadaki { get; set; }
        public Nullable<int> Tedad { get; set; }
    
        public virtual tbl_ShenasnamehMoshinAlat tbl_ShenasnamehMoshinAlat { get; set; }
    }
}
