//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ShenasnamehMoshinAlat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ShenasnamehMoshinAlat()
        {
            this.tbl_GhataatMasrafiMashinAlat = new HashSet<tbl_GhataatMasrafiMashinAlat>();
        }
    
        public long ID { get; set; }
        public string NameDastgha { get; set; }
        public string CodeDastghah { get; set; }
        public string ModelDastGhah { get; set; }
        public string Size { get; set; }
        public string Vazn { get; set; }
        public string Zarfiyat { get; set; }
        public string AmerMofid { get; set; }
        public string SharkatSazandeh { get; set; }
        public string KeshvarSazandeh { get; set; }
        public string TaiedKonnadeh { get; set; }
        public string AdressNamayandegi { get; set; }
        public string TelphoneNamayandegi { get; set; }
        public Nullable<bool> Bargh { get; set; }
        public Nullable<bool> Ab { get; set; }
        public Nullable<bool> Hava { get; set; }
        public Nullable<bool> Ghaz { get; set; }
        public Nullable<System.DateTime> TarikhSakht { get; set; }
        public Nullable<System.DateTime> TarikhBahrehBardari { get; set; }
        public Nullable<System.DateTime> TarikhTahiyeEttelaat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GhataatMasrafiMashinAlat> tbl_GhataatMasrafiMashinAlat { get; set; }
    }
}
