//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UsableMaterialsGhaleb
    {
        public long ID { get; set; }
        public long IDGhaleb { get; set; }
        public string Caption { get; set; }
        public string Type { get; set; }
        public string TimeServices { get; set; }
        public string UsableGhataatYadaki { get; set; }
        public string Peryod { get; set; }
        public string UsableMaterials { get; set; }
    }
}
