//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ghaleb
    {
        public long ID { get; set; }
        public string NameGhaleb { get; set; }
        public string Code { get; set; }
        public string TypeGhaleb { get; set; }
        public string Vazn { get; set; }
        public string UsableMaterials { get; set; }
        public string Address { get; set; }
        public string Tool { get; set; }
        public string Arz { get; set; }
        public string Ertefa { get; set; }
        public Nullable<System.DateTime> TarikhSakht { get; set; }
        public Nullable<System.DateTime> tarikhShorooBeKar { get; set; }
        public string sharayetneghahdari { get; set; }
        public string GensGhaleb { get; set; }
        public Nullable<bool> VaziyatGhaleb { get; set; }
        public string VaziyatKharid { get; set; }
        public string SystemKhoonakKonnadeh { get; set; }
        public string TypeGiris { get; set; }
        public string OmreMofid { get; set; }
        public string Sazandeh { get; set; }
    }
}
